# Generated by Django 3.0.7 on 2020-06-28 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='hours',
            field=models.PositiveIntegerField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='minutes',
            field=models.PositiveIntegerField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
